### ISSUE TITLE
Can't put websocket handle logic in go routine

### ISSUE THREAD

**Issue by s-patompong** [gofiber/websocket#12]
Hi!

First, gotta say I really like this library, but I have a problem where the client can't connect to the websocket when I put basic ping logic from the example in a different function and run it in goroutine. The example code is below.

Note: I've removed some log.Println to save some space here.

```go
package main

import (
	"log"

	"github.com/gofiber/fiber"
	"github.com/gofiber/websocket"
)

func handleConnection(c *websocket.Conn) {
	var (
		mt  int
		msg []byte
		err error
	)
	for {
		if mt, msg, err = c.ReadMessage(); err != nil {
			log.Println("read:", err)
			break
		}
		log.Printf("recv: %s", msg)

		if err = c.WriteMessage(mt, msg); err != nil {
			log.Println("write:", err)
			break
		}
	}
}

func main() {
	app := fiber.New()

	app.Use(func(c *fiber.Ctx) {
		if websocket.IsWebSocketUpgrade(c) {
			c.Locals("allowed", true)
			c.Next()
		}
	})

	app.Get("/ws/:id", websocket.New(func(c *websocket.Conn) {
		go handleConnection(c)
	}))

	log.Fatal(app.Listen(3000))
}
```
I'm I doing something wrong?

I had a look at gorilla/websocket example (https://github.com/gorilla/websocket/blob/master/examples/chat/client.go) and I see that they can use goroutine when serving the websocket.

**Comment by Fenny** [comment]
Hi @s-patompong, Fiber/Fasthttp uses a sync pool for the Context. This means that the moment you return from the handler the Ctx will be re-used and becomes invalid. Everything you execute in the handler is already running in a Go routine because fasthttp uses a workerpool by design.

So it's safe to use your function without spawning a second go routine:

```go
app.Get("/ws/:id", websocket.New(func(c *websocket.Conn) {
	// go handleConnection(c)
	handleConnection(c)
}))
```

**Comment by s-patompong** [comment]
That's neat! Thanks for the info 👍
