### ISSUE TITLE
How to know the protocol of requests

### ISSUE THREAD

**Issue by yuzuy** [gofiber/websocket#18]
Hi!
Can I know the protocol of requests?

**Comment by kiyonlin** [comment]
Hey @yuzuy I think [this](https://docs.gofiber.io/ctx#protocol) (`ctx.Protocol()`) will help you.

**Comment by yuzuy** [comment]
Hey @kiyonlin.
Does it mean that the protocol is ws or wss can be determined by whether `ctx.Protocol()` returns http or https?

**Comment by kiyonlin** [comment]
`websocket` is upgrader of `http`, so
```
http -> ws
https -> wss
```

**Comment by yuzuy** [comment]
Thanks for the info!
