### ISSUE TITLE
How to access the fiber.context

### ISSUE THREAD

**Issue by jason-shen** [gofiber/websocket#19]
Just wondering whats the correct.way to access the fiber context from this middleware cheers

**Comment by Fenny** [comment]
Hi @jason-shen, unfortunately you cannot access the fiber context within the websocket handler.
You have to create a middleware in front of the websocket upgrader to access the context before you upgrade to a socket connection.

**Comment by jason-shen** [comment]
> Hi @jason-shen, unfortunately you cannot access the fiber context within the websocket handler.
> You have to create a middleware in front of the websocket upgrader to access the context before you upgrade to a socket connection.

thanks for that, cheers
