### ISSUE TITLE
safari disconnection issue

### ISSUE THREAD

**Issue by jason-shen** [gofiber/websocket#23]
Hi All

i am experiencing an issue when disconnect from safari, i get a 1006 CloseAbnormalclosure which in chrome it gives a closeNormalClosure 1001 is the correct, this creates panic error on not removing the socket from my map, has anyone experience this issue?

or any help would be great 

cheers

Jason

**Comment by Fenny** [comment]
By any chance, you could share your code to re-produce the issue?

**Comment by jason-shen** [comment]
> By any chance, you could share your code to re-produce the issue?

Ok i will stripe this code out and create a repo tomorrow, thanks advanced

**Comment by jason-shen** [comment]
> By any chance, you could share your code to re-produce the issue?

sorry my mistake did do the defer close properly, its all good now, cheers for the nice lib
