### ISSUE TITLE
Unable to install package due to unknown revision of fasthttp/websocket (v1.4.3)

### ISSUE THREAD

**Issue by jar3b** [gofiber/websocket#24]
> go version

```
go version go1.15 linux/amd64
```

Hello, when I try to download package by `go get -u github.com/gofiber/websocket/v2` I get following error:

```
go: downloading github.com/fasthttp/websocket v1.4.3
go: golang.org/x/sys upgrade => v0.0.0-20200922070232-aee5d888a860
go: github.com/klauspost/compress upgrade => v1.11.0
go: github.com/valyala/fasthttp upgrade => v1.16.0
go: github.com/gofiber/fiber/v2 upgrade => v2.0.2
go: downloading golang.org/x/sys v0.0.0-20200922070232-aee5d888a860
../../../go/pkg/mod/github.com/gofiber/websocket/v2@v2.0.0/websocket.go:13:2: reading github.com/fasthttp/websocket/go.mod at revision v1.4.3: unknown revision v1.4.3
```

This is because latest tag for https://github.com/fasthttp/websocket is `v1.4.3-beta.2` 

I can offer next possible workarounds:
1. Use older (stable?) version: `github.com/fasthttp/websocket v1.4.2`
2. Use current beta `github.com/fasthttp/websocket v1.4.3-beta.2`
3. Wait for `fasthttp/websocket` stable `v1.4.3` release :)

Thanks!

**Comment by Fenny** [comment]
Fixed in https://github.com/gofiber/websocket/pull/25

**Comment by hrvatskibogmars** [comment]
Hey,

Is this still an issue? We have Dependabot on our repo and its reporting.
`
github.com/fasthttp/websocket@v1.4.3: reading github.com/fasthttp/websocket/go.mod at revision v1.4.3: unknown revision v1.4.3
`
I also see that on the master branch you still have an invalid version of a package?
`
github.com/fasthttp/websocket v1.4.3
`
