### ISSUE TITLE
Room or Broadcast option?

### ISSUE THREAD

**Issue by rebootcode** [gofiber/websocket#3]
Is there any Room based or Broadcast option?

Or do we need to store "each connection ID" to a specific name and emit for every user in the loop?

**Comment by Fenny** [comment]
Hi @rebootcode! The websocket API is based on [gorilla/websocket](https://github.com/gorilla/websocket) maybe you can check out their examples or browse trough the issues regarding your question.

https://github.com/gorilla/websocket/issues/46
https://github.com/gorilla/websocket/tree/master/examples
https://pkg.go.dev/github.com/gorilla/websocket?tab=doc

**Comment by jos-** [comment]
FYI I made a minimal chat example with a hub to which you can broadcast, see https://github.com/jos-/gofiber-websocket-chat-example

**Comment by thomasvvugt** [comment]
Hi @jos-, thanks for the example! Could you make a PR for this in our [recipes](https://github.com/gofiber/recipes) repository?

**Comment by jos-** [comment]
Sure, see https://github.com/gofiber/recipes/pull/39
