### ISSUE TITLE
unknown fasthttp revision: v1.4.3

### ISSUE THREAD

**Issue by tusharsadhwani** [gofiber/websocket#37]
I saw #32 

But I'm still getting this issue for some reason:

```console
❯ go get -u github.com/gofiber/websocket/v2
go: github.com/gofiber/websocket/v2 upgrade => v2.0.2
go get: github.com/gofiber/websocket/v2@v2.0.2 requires
        github.com/fasthttp/websocket@v1.4.3: reading github.com/fasthttp/websocket/go.mod at revision v1.4.3: unknown revision v1.4.3
```

**Comment by tusharsadhwani** [comment]
Temporarily fixed by pinning websocket version to 2.0.1

**Comment by ReneWerner87** [comment]
Fixed with #32

**Comment by tusharsadhwani** [comment]
I said I had seen #32, which was marked as closed but i was still getting the issue. I'll re-verify this and re-open if the issue still exists for me.

**Comment by ReneWerner87** [comment]
The pull request is not released yet, will do it tomorrow.
