### ISSUE TITLE
IsWebsocketUpgrade returning false

### ISSUE THREAD

**Issue by Nv7-GitHub** [gofiber/websocket#40]
I copied the code from the example into my test server. It worked fine on localhost using https://www.websocket.org/echo.html, but when I deployed it and used `wss://api.nv7haven.tk/ws/123?v=1.0`, it is returning a 426. I put a print statement, and its returning a 426 because IsWebsocketUpgrade is returning false. Why is it returning false, and how can I fix this?

**Comment by ReneWerner87** [comment]
Have you found the error in the meantime?

Otherwise I need sample code to reproduce.

**Comment by ReneWerner87** [comment]
@Nv7-GitHub

**Comment by Nv7-GitHub** [comment]
The issue was with my hosting provider, sorry for the slow response, I'm going to close this now
