### ISSUE TITLE
Error getting websocket middleware

### ISSUE THREAD

**Issue by angelogeminiani** [gofiber/websocket#7]
When I try to use websocket with go get I receive this error:

go get: github.com/gofiber/websocket@v0.4.0 requires
        github.com/gofiber/fiber@v1.10.0: reading github.com/gofiber/fiber/go.mod at revision v1.10.0: unknown revision refs/tags/v1.10.0

**Comment by Fenny** [comment]
Hey @angelogeminiani should be fixed in https://github.com/gofiber/websocket/releases/tag/v0.4.1
