### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by bitdom8** [gofiber/websocket#76]
cannot use c (type *"github.com/gofiber/fiber/v2".Ctx) as type *"github.com/gofiber/fiber".Ctx in argument to "github.com/gofiber/websocket".IsWebSocketUpgrade.\main.go:67:34: cannot use "github.com/gofiber/websocket".New(func literal) (type func(*"github.com/gofiber/fiber".Ctx)) as type func(*"github.com/gofiber/fiber/v2".Ctx) error in argument to app.Get

**Comment by MAHakeem-MK** [comment]
Please share error prone code also to reproduce this error.

**Comment by bitdom8** [comment]
It is fixed now, after go tidy and couple of instructions on google. Thank u
