### ISSUE TITLE
Example of showing as a separate function

### ISSUE THREAD

**Issue by saul-data** [gofiber/websocket#89]
I can use the example in the readme file but I struggled to create a separate function. If I had a separate file to the router to keep all my websocket functions, what would that look like?

**Comment by surjit** [comment]
I'm also looking for same example code.  below not working even not throwing any error

```
app.Get("/ws", TestSocket)
```

```
func TestSocket(c *fiber.Ctx) error {
	websocket.New(func(c *websocket.Conn) {
		var (
			mt  int
			msg []byte
			err error
		)
		for {
			if mt, msg, err = c.ReadMessage(); err != nil {
				log.Println("read:", err)
				break
			}
			log.Printf("recv: %s", msg)

			if err = c.WriteMessage(mt, msg); err != nil {
				log.Println("write:", err)
				break
			}
		}

	})

	return c.SendString("x")
}
```

**Comment by GarryGaller** [comment]
How do I pass the *fiber.Ctx object to the websocket handler?

**Comment by ReneWerner87** [comment]
this is not possible, because you have a different object for the connection there
